version: v2.13.1
plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: "v0.0.0-20260808063849-8649a03c818a"
  - module: "go.kenn.io/kit"
    import: "go.kenn.io/kit/lint/gclplugin"
    version: "v0.25.1-0.20260918202731-04a175847323"
