// ABOUTME: `skills` command group: install and list the AgentsView skill
// ABOUTME: files that teach coding-agent harnesses to search session history.
package main

import (
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	gitrepo "go.kenn.io/kit/git/repo"

	"go.kenn.io/agentsview/internal/skills"
)

// skillFileName is the file every harness's skill directory installs, as
// documented on skills.TargetDir.
const skillFileName = "SKILL.md"

func newSkillsCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:          "skills",
		Short:        "Install and list AgentsView skills for coding-agent harnesses",
		GroupID:      groupMeta,
		SilenceUsage: true,
		Args:         cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return cmd.Help()
		},
	}
	cmd.PersistentFlags().String("server", "",
		"Remote daemon URL to bake into generated skill examples "+
			"(or AGENTSVIEW_SKILLS_SERVER); pass --server \"\" to un-bake")
	cmd.PersistentFlags().String("server-token-file", "",
		"Token file path to bake into generated skill examples "+
			"(or AGENTSVIEW_SKILLS_SERVER_TOKEN_FILE)")
	cmd.AddCommand(newSkillsInstallCommand())
	cmd.AddCommand(newSkillsListCommand())
	return cmd
}

func newSkillsInstallCommand() *cobra.Command {
	var (
		harnessNames []string
		project      bool
		force        bool
	)
	cmd := &cobra.Command{
		Use:          "install",
		Short:        "Install AgentsView skill files for coding-agent harnesses",
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			harnesses, err := resolveSkillHarnesses(harnessNames)
			if err != nil {
				return err
			}
			base, err := skillsBaseDir(cmd.Context(), project)
			if err != nil {
				return err
			}
			remote, err := skillRemoteFromFlags(cmd)
			if err != nil {
				return err
			}
			return runSkillsInstall(cmd.OutOrStdout(), harnesses, base, force, remote)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&harnessNames, "harness", nil,
		"Harness to install for (claude or agents); repeatable, default both")
	flags.BoolVar(&project, "project", false,
		"Install into the project (git root of the current directory) "+
			"instead of the user home directory")
	flags.BoolVar(&force, "force", false,
		"Overwrite files that were modified or were not generated by agentsview")
	return cmd
}

// runSkillsInstall renders and writes each harness's skill file under base,
// printing one line per target. It processes every target before returning
// so a refusal on one harness never blocks another, then reports a non-nil
// error if any target was refused.
func runSkillsInstall(
	out io.Writer, harnesses []skills.Harness, base string, force bool,
	remote skillRemoteSource,
) error {
	var refused []string
	for _, h := range harnesses {
		dir := skills.TargetDir(h, base)
		path := filepath.Join(dir, skillFileName)

		existing, err := readSkillFile(path)
		if err != nil {
			return err
		}
		rendered, err := skills.Render(h, version, remote.resolve(existing))
		if err != nil {
			return err
		}
		state := skills.Classify(existing, rendered)

		if !force && (state == skills.StateModified || state == skills.StateForeign) {
			fmt.Fprintf(out, "%s was modified (or not generated); use --force to overwrite\n", path)
			refused = append(refused, path)
			continue
		}

		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("skills: create %s: %w", dir, err)
		}
		if err := os.WriteFile(path, []byte(rendered.Content), 0o644); err != nil {
			return fmt.Errorf("skills: write %s: %w", path, err)
		}

		switch state {
		case skills.StateMissing:
			fmt.Fprintf(out, "installed %s\n", path)
		case skills.StateCurrent:
			fmt.Fprintf(out, "up to date %s\n", path)
		default: // StateStale, or StateModified/StateForeign forced
			fmt.Fprintf(out, "updated %s\n", path)
		}
	}

	if len(refused) > 0 {
		return fmt.Errorf(
			"skills install: %d target(s) refused; rerun with --force to overwrite",
			len(refused),
		)
	}
	return nil
}

func newSkillsListCommand() *cobra.Command {
	var project bool
	cmd := &cobra.Command{
		Use:          "list",
		Short:        "List AgentsView skill files and their install state",
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			base, err := skillsBaseDir(cmd.Context(), project)
			if err != nil {
				return err
			}
			remote, err := skillRemoteFromFlags(cmd)
			if err != nil {
				return err
			}
			rows, err := listSkillRows(base, project, remote)
			if err != nil {
				return err
			}
			if outputFormat(cmd) == "json" {
				return json.MarshalEncode(jsontext.NewEncoder(cmd.OutOrStdout()), rows)
			}
			return printSkillListHuman(cmd.OutOrStdout(), rows)
		},
	}
	flags := cmd.Flags()
	flags.BoolVar(&project, "project", false,
		"List project-level (git root of the current directory) installs "+
			"instead of the user home directory")
	registerFormatFlags(flags)
	return cmd
}

// skillListRow is one row of `skills list` output, in both human and JSON form.
type skillListRow struct {
	Harness string `json:"harness"`
	Level   string `json:"level"`
	State   string `json:"state"`
	Path    string `json:"path"`
}

// listSkillRows classifies every harness's skill file under base against a
// fresh render.
func listSkillRows(
	base string, project bool, remote skillRemoteSource,
) ([]skillListRow, error) {
	level := "user"
	if project {
		level = "project"
	}

	harnesses := skills.AllHarnesses()
	rows := make([]skillListRow, 0, len(harnesses))
	for _, h := range harnesses {
		dir := skills.TargetDir(h, base)
		path := filepath.Join(dir, skillFileName)

		existing, err := readSkillFile(path)
		if err != nil {
			return nil, err
		}
		rendered, err := skills.Render(h, version, remote.resolve(existing))
		if err != nil {
			return nil, err
		}
		state := skills.Classify(existing, rendered)

		rows = append(rows, skillListRow{
			Harness: string(h),
			Level:   level,
			State:   skillStateString(state),
			Path:    path,
		})
	}
	return rows, nil
}

func printSkillListHuman(w io.Writer, rows []skillListRow) error {
	fmt.Fprintf(w, "%-8s  %-8s  %-8s  %s\n", "HARNESS", "LEVEL", "STATE", "PATH")
	for _, r := range rows {
		fmt.Fprintf(w, "%-8s  %-8s  %-8s  %s\n", r.Harness, r.Level, r.State, r.Path)
	}
	return nil
}

func skillStateString(s skills.InstalledState) string {
	switch s {
	case skills.StateMissing:
		return "missing"
	case skills.StateCurrent:
		return "current"
	case skills.StateStale:
		return "stale"
	case skills.StateModified:
		return "modified"
	case skills.StateForeign:
		return "foreign"
	default:
		return "unknown"
	}
}

// readSkillFile reads path, returning nil (not an empty slice) when the file
// does not exist so the result matches skills.Classify's "missing" contract.
func readSkillFile(path string) ([]byte, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("skills: read %s: %w", path, err)
	}
	return content, nil
}

// skillRemoteSource holds the remote-daemon inputs for one skills command,
// so each target file can be resolved against what it already has baked in.
type skillRemoteSource struct {
	flag skills.Remote
	// explicit is true when --server or --server-token-file was passed, in
	// which case the flag value wins even if it is empty. That is the only
	// way to un-bake a remote and go back to a local-SQLite skill.
	explicit bool
	env      skills.Remote
}

// resolve picks the remote to render for one skill file. Explicit flags win.
// Otherwise an installed file decides, including when it bakes no remote at
// all: "this skill is local" is recorded intent too. The environment only
// seeds a file that is not there yet, so exporting AGENTSVIEW_SKILLS_SERVER
// cannot retroactively mark every installed skill stale in `skills list`.
func (s skillRemoteSource) resolve(existing []byte) skills.Remote {
	if s.explicit {
		return s.flag
	}
	if len(existing) > 0 {
		return skills.ParseRemote(string(existing))
	}
	return s.env
}

// skillRemoteFromFlags reads the remote-daemon inputs for skill examples.
// The environment variables are skills-only on purpose and are named apart
// from AGENTSVIEW_SERVER_TOKEN so they cannot be mistaken for a default read
// path for `session` commands, which have none. A token file without a
// server is an error.
func skillRemoteFromFlags(cmd *cobra.Command) (skillRemoteSource, error) {
	server, err := cmd.Flags().GetString("server")
	if err != nil {
		return skillRemoteSource{}, err
	}
	tokenFile, err := cmd.Flags().GetString("server-token-file")
	if err != nil {
		return skillRemoteSource{}, err
	}
	src := skillRemoteSource{
		flag: skills.Remote{
			Server:    strings.TrimSpace(server),
			TokenFile: strings.TrimSpace(tokenFile),
		},
		explicit: cmd.Flags().Changed("server") ||
			cmd.Flags().Changed("server-token-file"),
		env: skills.Remote{
			Server:    strings.TrimSpace(os.Getenv("AGENTSVIEW_SKILLS_SERVER")),
			TokenFile: strings.TrimSpace(os.Getenv("AGENTSVIEW_SKILLS_SERVER_TOKEN_FILE")),
		},
	}
	if src.explicit {
		if src.flag.TokenFile != "" && src.flag.Server == "" {
			return skillRemoteSource{}, errors.New(
				"skills: --server-token-file requires --server")
		}
		return src, src.flag.Validate()
	}
	if src.env.TokenFile != "" && src.env.Server == "" {
		return skillRemoteSource{}, errors.New(
			"skills: AGENTSVIEW_SKILLS_SERVER_TOKEN_FILE requires AGENTSVIEW_SKILLS_SERVER")
	}
	return src, src.env.Validate()
}

// resolveSkillHarnesses maps --harness flag values to skills.Harness,
// defaulting to every harness when none were given.
func resolveSkillHarnesses(names []string) ([]skills.Harness, error) {
	if len(names) == 0 {
		return skills.AllHarnesses(), nil
	}
	out := make([]skills.Harness, 0, len(names))
	for _, name := range names {
		switch name {
		case string(skills.HarnessClaude):
			out = append(out, skills.HarnessClaude)
		case string(skills.HarnessAgents):
			out = append(out, skills.HarnessAgents)
		default:
			return nil, fmt.Errorf("skills: unknown --harness %q (want claude or agents)", name)
		}
	}
	return out, nil
}

// skillsBaseDir resolves the install base: the user home directory by
// default, or the git root of the current directory (falling back to the
// current directory itself outside a repo) when project is true.
func skillsBaseDir(ctx context.Context, project bool) (string, error) {
	if !project {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("skills: resolve home directory: %w", err)
		}
		return home, nil
	}

	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("skills: resolve working directory: %w", err)
	}

	opCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	root, err := gitrepo.Root(opCtx, cwd)
	if err != nil || root == "" {
		return cwd, nil
	}
	return root, nil
}
