// Code generated by "enumer -type=CapabilitySupport -json -text -transform=snake -trimprefix=Capability -output=capabilitysupport_enumer.go"; DO NOT EDIT.

package parser

import (
	"encoding/json/v2"
	"fmt"
	"slices"
	"strings"
)

const _CapabilitySupportName = "unsupportedsupportednot_applicable"

var _CapabilitySupportIndex = [...]uint8{0, 11, 20, 34}

const _CapabilitySupportLowerName = "unsupportedsupportednot_applicable"

func (i CapabilitySupport) String() string {
	if i >= CapabilitySupport(len(_CapabilitySupportIndex)-1) {
		return fmt.Sprintf("CapabilitySupport(%d)", i)
	}
	return _CapabilitySupportName[_CapabilitySupportIndex[i]:_CapabilitySupportIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CapabilitySupportNoOp() {
	var x [1]struct{}
	_ = x[CapabilityUnsupported-(0)]
	_ = x[CapabilitySupported-(1)]
	_ = x[CapabilityNotApplicable-(2)]
}

var _CapabilitySupportValues = []CapabilitySupport{CapabilityUnsupported, CapabilitySupported, CapabilityNotApplicable}

var _CapabilitySupportNameToValueMap = map[string]CapabilitySupport{
	_CapabilitySupportName[0:11]:       CapabilityUnsupported,
	_CapabilitySupportLowerName[0:11]:  CapabilityUnsupported,
	_CapabilitySupportName[11:20]:      CapabilitySupported,
	_CapabilitySupportLowerName[11:20]: CapabilitySupported,
	_CapabilitySupportName[20:34]:      CapabilityNotApplicable,
	_CapabilitySupportLowerName[20:34]: CapabilityNotApplicable,
}

var _CapabilitySupportNames = []string{
	_CapabilitySupportName[0:11],
	_CapabilitySupportName[11:20],
	_CapabilitySupportName[20:34],
}

// CapabilitySupportString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CapabilitySupportString(s string) (CapabilitySupport, error) {
	if val, ok := _CapabilitySupportNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CapabilitySupportNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CapabilitySupport values", s)
}

// CapabilitySupportValues returns all values of the enum
func CapabilitySupportValues() []CapabilitySupport {
	return _CapabilitySupportValues
}

// CapabilitySupportStrings returns a slice of all String values of the enum
func CapabilitySupportStrings() []string {
	strs := make([]string, len(_CapabilitySupportNames))
	copy(strs, _CapabilitySupportNames)
	return strs
}

// IsACapabilitySupport returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CapabilitySupport) IsACapabilitySupport() bool {
	return slices.Contains(_CapabilitySupportValues, i)
}

// MarshalJSON implements the json.Marshaler interface for CapabilitySupport
func (i CapabilitySupport) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CapabilitySupport
func (i *CapabilitySupport) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CapabilitySupport should be a string, got %s", data)
	}

	var err error
	*i, err = CapabilitySupportString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for CapabilitySupport
func (i CapabilitySupport) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CapabilitySupport
func (i *CapabilitySupport) UnmarshalText(text []byte) error {
	var err error
	*i, err = CapabilitySupportString(string(text))
	return err
}
