package parser

import (
	"database/sql"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestOpenCodeV2BetaWorkflow(t *testing.T) {
	// The beta CLI produced these tables through four real prompts. Keeping
	// its schema catches assumptions about legacy tables that hand-built
	// projection-only fixtures cannot catch.
	raw, err := os.ReadFile("testdata/opencode_v2/beta.sql")
	require.NoError(t, err)
	path := filepath.Join(t.TempDir(), "opencode.db")
	writer, err := sql.Open("sqlite3", path)
	require.NoError(t, err)
	t.Cleanup(func() { writer.Close() })
	_, err = writer.ExecContext(t.Context(), string(raw))
	require.NoError(t, err)

	const id = "ses_f78f34fafffeIugr4PB2oXkVD0"
	metas, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	require.Len(t, metas, 3)
	watermarks, err := ListOpenCodeSessionWatermarkMeta(path)
	require.NoError(t, err)
	require.Len(t, watermarks, 3)
	assert.True(t, watermarks[0].WatermarkOnly)
	assert.True(t, OpenCodeSQLiteSessionExists(t.Context(), path, id))
	_, composite, found, err := openCodeSQLiteSessionWatermarkOnly(t.Context(), path, id)
	require.NoError(t, err)
	assert.True(t, composite)
	assert.True(t, found)

	sess, msgs, err := parseOpenCodeDBSession(path, id, "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	assert.Equal(t, "/workspace/project-a", sess.Cwd)
	assert.Equal(t, 2, sess.UserMessageCount)
	assert.True(t, time.UnixMilli(1788972159327).Equal(sess.EndedAt))
	require.Len(t, msgs, 5)
	assert.Contains(t, msgs[0].Content, "Read input.txt using the read tool.")
	require.Len(t, msgs[1].ToolCalls, 1)
	call := msgs[1].ToolCalls[0]
	assert.Equal(t, "read", call.ToolName)
	assert.JSONEq(t, `{"path":"/workspace/project-a/input.txt"}`, call.InputJSON)
	require.Len(t, call.ResultEvents, 1)
	assert.Equal(t, "Read file /workspace/project-a/input.txt, lines 1-3\n1: alpha\n2: beta\n3: gamma", call.ResultEvents[0].Content)
	assert.Contains(t, msgs[2].Content, "**Number of lines:** 3")
	assert.Contains(t, msgs[4].Content, "[/Thinking]\nbeta")
	assert.Equal(t, "big-pickle", msgs[4].Model)
	assert.Equal(t, 26, msgs[4].OutputTokens)
	assert.Equal(t, 7154, msgs[4].ContextTokens)

	_, failed, err := parseOpenCodeDBSession(path, "ses_f78ee770effebwbWXea2fzwUIu", "host-a")
	require.NoError(t, err)
	require.Len(t, failed, 3)
	require.Len(t, failed[1].ToolCalls, 1)
	shell := failed[1].ToolCalls[0]
	assert.Equal(t, "shell", shell.ToolName)
	require.Len(t, shell.ResultEvents, 1)
	assert.Equal(t, "errored", shell.ResultEvents[0].Status)
	assert.Contains(t, shell.ResultEvents[0].Content, "Command exited with code 7.")

	// Streaming finalization updates only the projection, not session metadata.
	before, digest, composite, err := openCodeSessionCompositeMtime(t.Context(), writer, path, id)
	require.NoError(t, err)
	assert.True(t, composite)
	_, err = writer.ExecContext(t.Context(), `UPDATE session_message SET time_updated = 1788972160000,
	 data = json_set(data, '$.content[1].text', 'updated beta') WHERE session_id = ? AND seq = 25`, id)
	require.NoError(t, err)
	after, err := OpenCodeSourceMtime(t.Context(), path+"#"+id)
	require.NoError(t, err)
	assert.Greater(t, after, before*1_000_000)
	_, updatedDigest, _, err := openCodeSessionCompositeMtime(t.Context(), writer, path, id)
	require.NoError(t, err)
	assert.NotEqual(t, digest, updatedDigest)
	_, msgs, err = parseOpenCodeDBSession(path, id, "host-a")
	require.NoError(t, err)
	require.Len(t, msgs, 5)
	assert.Contains(t, msgs[4].Content, "[/Thinking]\nupdated beta")

	// An empty v2 session must not try to load nonexistent v1 message tables.
	_, err = writer.ExecContext(t.Context(), "DELETE FROM session_message WHERE session_id = ?", id)
	require.NoError(t, err)
	sess, msgs, err = parseOpenCodeDBSession(path, id, "host-a")
	require.NoError(t, err)
	assert.Nil(t, sess)
	assert.Empty(t, msgs)
}

func TestOpenCodeV2CapturedWorkflow(t *testing.T) {
	// Generated by OpenCode 1.18.25's /api/session v2 API, with scratch paths
	// replaced. This fixture is producer output, not assembled by the simulator.
	raw, err := os.ReadFile("testdata/opencode_v2/messages.json")
	require.NoError(t, err)
	var rows []struct {
		ID      string         `json:"id"`
		Type    string         `json:"type"`
		Seq     int64          `json:"seq"`
		Created int64          `json:"time_created"`
		Updated int64          `json:"time_updated"`
		Data    jsontext.Value `json:"data"`
	}
	require.NoError(t, json.Unmarshal(raw, &rows))
	path, seed, writer := newTestDB(t)
	seed.AddProject("project-a", "/workspace/project-a")
	seed.AddSession("ses_captured", "project-a", "", "Count lines", 1788899250985, 1788899253026)
	_, err = writer.ExecContext(t.Context(), openCodeV2TestSchema)
	require.NoError(t, err)
	for _, row := range rows {
		_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES (?, 'ses_captured', ?, ?, ?, ?, ?)`, row.ID, row.Type, row.Seq, row.Created, row.Updated, string(row.Data))
		require.NoError(t, err)
	}
	sess, msgs, err := parseOpenCodeDBSession(path, "ses_captured", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	require.Len(t, msgs, 4)
	assert.Equal(t, 1, sess.UserMessageCount)
	assert.Equal(t, "Read input.txt using the read tool. Reply with the three words in order and the number of lines. Do not edit files or run other commands.", msgs[0].Content)
	assert.True(t, msgs[1].HasThinking)
	require.Len(t, msgs[1].ToolCalls, 1)
	call := msgs[1].ToolCalls[0]
	assert.Equal(t, "read", call.ToolName)
	assert.JSONEq(t, `{"path":"input.txt"}`, call.InputJSON)
	require.Len(t, call.ResultEvents, 1)
	assert.Equal(t, "alpha\nbeta\ngamma\n", call.ResultEvents[0].Content)
	assert.True(t, msgs[2].IsSystem)
	assert.Equal(t, "The three words in order are: **alpha**, **beta**, **gamma**.\n\nThe file has **3 lines**.", msgs[3].Content)
	assert.Equal(t, "big-pickle", msgs[3].Model)
	assert.Equal(t, 25, msgs[3].OutputTokens)
	assert.Equal(t, 3487, msgs[3].ContextTokens)
}

// Projection schema from anomalyco/opencode dff8fbc149fb, core/src/session/sql.ts.
// The producer retains session/message/part for v1 sessions in the same DB.
const openCodeV2TestSchema = `CREATE TABLE session_message (
 id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES session(id) ON DELETE CASCADE,
 type TEXT NOT NULL, seq INTEGER NOT NULL, time_created INTEGER NOT NULL,
 time_updated INTEGER NOT NULL, data TEXT NOT NULL
);
CREATE UNIQUE INDEX session_message_session_seq_idx ON session_message(session_id, seq);
CREATE INDEX session_message_session_type_seq_idx ON session_message(session_id, type, seq);
CREATE INDEX session_message_session_time_created_id_idx ON session_message(session_id, time_created, id);
CREATE INDEX session_message_time_created_idx ON session_message(time_created);`

func TestOpenCodeV2Projection(t *testing.T) {
	path, seed, writer := newTestDB(t)
	t.Cleanup(func() { writer.Close() })
	seed.AddProject("project-a", "/workspace/project-a")
	seed.AddSession("ses_v2", "project-a", "ses_parent", "", 1700000000000, 1700000060000)
	_, err := writer.ExecContext(t.Context(), openCodeV2TestSchema)
	require.NoError(t, err)
	// IDs and timestamps deliberately disagree with event sequence order.
	_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES
 ('msg_a', 'ses_v2', 'assistant', 20, 1700000000000, 1700000000000,
 '{"agent":"build","model":{"id":"gpt-5.4","providerID":"openai"},"time":{"created":1700000000000},"content":[{"type":"text","id":"txt_a","text":"Draft"}]}'),
 ('msg_z', 'ses_v2', 'user', 10, 1700000000100, 1700000000100,
 '{"text":"Check the query","files":[],"agents":[],"time":{"created":1700000000100}}')`)
	require.NoError(t, err)
	sess, msgs, err := parseOpenCodeDBSession(path, "ses_v2", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess, "v2 conversation must be imported")
	require.Len(t, msgs, 2)
	assert.Equal(t, "Check the query", msgs[0].Content)
	assert.Equal(t, "Draft", msgs[1].Content)
	assert.Equal(t, "opencode:ses_parent", sess.ParentSessionID)
	assert.Equal(t, "Check the query", sess.FirstMessage)
	assert.Equal(t, "/workspace/project-a", sess.Cwd)
	before, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)

	// Text.Ended, Tool.Success and Step.Ended update a projection in place.
	// A high session timestamp must not hide this child-only update.
	_, err = writer.ExecContext(t.Context(), `UPDATE session_message SET time_updated = 1700000001000, data =
 '{"agent":"build","model":{"id":"gpt-5.4","providerID":"openai"},
 "time":{"created":1700000000000,"completed":1700000001000},
 "tokens":{"input":100,"output":20,"reasoning":5,"cache":{"read":30,"write":0}},
 "content":[{"type":"reasoning","id":"z","text":"Inspect the plan"},
 {"type":"tool","id":"call_a","name":"bash","time":{"created":1700000000000,"completed":1700000000900},
 "state":{"status":"completed","input":{"command":"explain query"},"structured":{},"content":[{"type":"text","text":"Index scan"}]}},
 {"type":"text","id":"a","text":"Use the index"}]}' WHERE id = 'msg_a'`)
	require.NoError(t, err)
	after, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	require.Len(t, after, 1)
	assert.Equal(t, before[0].FileMtime, after[0].FileMtime)
	assert.NotEqual(t, before[0].ChildDigest, after[0].ChildDigest)
	mtime, digest, composite, err := openCodeSessionCompositeMtime(t.Context(), writer, path, "ses_v2")
	require.NoError(t, err)
	assert.True(t, composite)
	assert.Equal(t, after[0].ChildDigest, digest)
	assert.Equal(t, after[0].FileMtime, mtime*1_000_000)
	sess, msgs, err = parseOpenCodeDBSession(path, "ses_v2", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	require.Len(t, msgs, 2)
	assert.Equal(t, "[Thinking]\nInspect the plan\n[/Thinking]\nUse the index", msgs[1].Content)
	assert.True(t, msgs[1].HasThinking)
	assert.Equal(t, "gpt-5.4", msgs[1].Model)
	assert.JSONEq(t, `{"input_tokens":100,"output_tokens":20,"cache_read_input_tokens":30,"cache_creation_input_tokens":0}`, string(msgs[1].TokenUsage))
	require.Len(t, msgs[1].ToolCalls, 1)
	call := msgs[1].ToolCalls[0]
	assert.Equal(t, "call_a", call.ToolUseID)
	assert.Equal(t, "bash", call.ToolName)
	assert.JSONEq(t, `{"command":"explain query"}`, call.InputJSON)
	require.Len(t, call.ResultEvents, 1)
	assert.Equal(t, "completed", call.ResultEvents[0].Status)
	assert.Equal(t, "Index scan", call.ResultEvents[0].Content)

	// Revert.Committed removes later projection rows without lowering session time.
	_, err = writer.ExecContext(t.Context(), `DELETE FROM session_message WHERE session_id = 'ses_v2' AND seq > 10`)
	require.NoError(t, err)
	reverted, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	assert.NotEqual(t, after[0].ChildDigest, reverted[0].ChildDigest)
	_, msgs, err = parseOpenCodeDBSession(path, "ses_v2", "host-a")
	require.NoError(t, err)
	require.Len(t, msgs, 1)
	assert.Equal(t, "Check the query", msgs[0].Content)
}

func TestOpenCodeV2MixedDatabase(t *testing.T) {
	path, seed, writer := newTestDB(t)
	_, err := writer.ExecContext(t.Context(), openCodeV2TestSchema)
	require.NoError(t, err)
	seed.AddProject("project-a", "/workspace/project-a")
	for _, id := range []string{"ses_v1", "ses_v2"} {
		seed.AddSession(id, "project-a", "", "Conversation", 1700000000000, 1700000001000)
		seed.AddMessage("msg_"+id, id, 1700000000000, 1700000000000, `{"role":"user"}`)
		seed.AddPart("prt_"+id, "msg_"+id, id, 1700000000000, 1700000000000, `{"type":"text","text":"Legacy conversation"}`)
	}
	_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES ('msg_ses_v2', 'ses_v2', 'user', 1, 1700000000000, 1700000000000, '{"text":"Projected conversation"}')`)
	require.NoError(t, err)
	for _, tc := range []struct{ id, text string }{{"ses_v1", "Legacy conversation"}, {"ses_v2", "Projected conversation"}} {
		t.Run(tc.id, func(t *testing.T) {
			assert.True(t, OpenCodeSQLiteSessionExists(t.Context(), path, tc.id))
			_, msgs, err := parseOpenCodeDBSession(path, tc.id, "host-a")
			require.NoError(t, err)
			require.Len(t, msgs, 1)
			assert.Equal(t, tc.text, msgs[0].Content)
		})
	}
}

func TestOpenCodeV2ToolStates(t *testing.T) {
	for _, tc := range []struct{ name, tool, state, status, text string }{
		{"structured", "custom", `{"status":"completed","input":{},"structured":{"content":[1,2],"exit":"other"},"content":[{"type":"text","text":"Done"}]}`, "completed", "Done"},
		{"pending", "bash", `{"status":"pending","input":"{\"command\":"}`, "", ""},
		{"streaming", "shell", `{"status":"streaming","input":"{\"command\":"}`, "", ""},
		{"running", "bash", `{"status":"running","input":{"command":"query"},"structured":{},"content":[]}`, "", ""},
		{"failed", "read", `{"status":"error","input":{"path":"missing.txt"},"structured":{},"content":[],"error":{"type":"unknown","message":"File missing"}}`, "errored", "File missing"},
		{"exit", "bash", `{"status":"completed","input":{"command":"false"},"structured":{"exit":1},"content":[{"type":"text","text":"Command exited with code 1."}]}`, "errored", "Command exited with code 1."},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path, seed, writer := newTestDB(t)
			seed.AddProject("project-a", "/workspace/project-a")
			seed.AddSession("ses_a", "project-a", "", "", 1700000000000, 1700000001000)
			_, err := writer.ExecContext(t.Context(), openCodeV2TestSchema)
			require.NoError(t, err)
			_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES ('msg_a', 'ses_a', 'assistant', 1, 1700000000000, 1700000001000, ?)`,
				fmt.Sprintf(`{"content":[{"type":"tool","id":"call_a","name":%q,"state":%s,"time":{"created":1700000000000,"completed":1700000001000}}]}`, tc.tool, tc.state))
			require.NoError(t, err)
			_, msgs, err := parseOpenCodeDBSession(path, "ses_a", "host-a")
			require.NoError(t, err)
			require.Len(t, msgs, 1)
			require.Len(t, msgs[0].ToolCalls, 1)
			call := msgs[0].ToolCalls[0]
			if tc.status == "" {
				assert.Empty(t, call.ResultEvents)
			} else {
				require.Len(t, call.ResultEvents, 1)
				assert.Equal(t, tc.status, call.ResultEvents[0].Status)
				assert.Equal(t, tc.text, call.ResultEvents[0].Content)
			}
		})
	}
}

func TestOpenCodeV2MessageKinds(t *testing.T) {
	for _, tc := range []struct {
		kind, data, content                   string
		system, compact, tool, usage, invalid bool
	}{
		{kind: "system", data: `{"text":"System context"}`, content: "System context", system: true},
		{kind: "synthetic", data: `{"text":"Injected context"}`, content: "Injected context", system: true},
		{kind: "skill", data: `{"skill":"skill_a","name":"review","text":"Review instructions"}`, content: "Review instructions", system: true},
		{kind: "compaction", data: `{"status":"completed","summary":"Earlier work summary","recent":"recent context","reason":"auto"}`, content: "Earlier work summary", system: true, compact: true},
		{kind: "compaction", data: `{"status":"running","summary":"Partial summary","recent":"","reason":"manual"}`, content: "Partial summary", system: true},
		{kind: "user", data: `{"text":"","files":[{"name":"input.txt","mime":"text/plain","data":"YWxwaGEK","source":{"type":"inline"}}]}`, content: "[Attachment: input.txt]\nalpha\n"},
		{kind: "user", data: `{"text":"Inspect this","files":[{"name":"plot.png","mime":"image/png","data":"","source":{"type":"inline"}}]}`, content: "Inspect this\n[Attachment: plot.png]"},
		{kind: "user", data: `{"text":"","files":[{"name":"input.txt","mime":"text/plain","uri":"file:///workspace/project-a/input.txt"}]}`, content: "[Attachment: input.txt]"},
		{kind: "shell", data: `{"command":"echo hello","callID":"call_shell","output":"hello\n","time":{"created":1700000000000,"completed":1700000001000}}`, content: "echo hello", tool: true},
		{kind: "shell", data: `{"command":"echo hello","shellID":"shell_a","status":"exited","exit":0,"output":{"output":"hello\n","cursor":6,"size":6,"truncated":false},"time":{"created":1700000000000,"completed":1700000001000}}`, content: "echo hello", tool: true},
		{kind: "assistant", data: `{"model":{"id":"gpt-5.4"},"content":[],"tokens":{"input":0,"output":0,"reasoning":0,"cache":{"read":0,"write":0}}}`, usage: true},
		{kind: "user", data: `{"text":`, invalid: true},
	} {
		t.Run(tc.kind, func(t *testing.T) {
			path, seed, writer := newTestDB(t)
			seed.AddProject("project-a", "/workspace/project-a")
			seed.AddSession("ses_a", "project-a", "", "", 1700000000000, 1700000001000)
			_, err := writer.ExecContext(t.Context(), openCodeV2TestSchema)
			require.NoError(t, err)
			_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES ('msg_a', 'ses_a', ?, 1, 1700000000000, 1700000001000, ?)`, tc.kind, tc.data)
			require.NoError(t, err)
			sess, msgs, err := parseOpenCodeDBSession(path, "ses_a", "host-a")
			if tc.invalid {
				require.Error(t, err)
				assert.Nil(t, sess)
				return
			}
			require.NoError(t, err)
			require.NotNil(t, sess)
			require.Len(t, msgs, 1)
			assert.Equal(t, tc.content, msgs[0].Content)
			assert.Equal(t, tc.system, msgs[0].IsSystem)
			assert.Equal(t, tc.compact, msgs[0].IsCompactBoundary)
			assert.Equal(t, tc.tool, msgs[0].HasToolUse)
			if tc.system {
				assert.Zero(t, sess.UserMessageCount)
			}
			if tc.tool {
				require.Len(t, msgs[0].ToolCalls, 1)
				assert.JSONEq(t, `{"command":"echo hello"}`, msgs[0].ToolCalls[0].InputJSON)
				require.Len(t, msgs[0].ToolCalls[0].ResultEvents, 1)
				assert.Equal(t, "hello\n", msgs[0].ToolCalls[0].ResultEvents[0].Content)
			}
			if tc.usage {
				assert.Equal(t, "gpt-5.4", msgs[0].Model)
				assert.True(t, msgs[0].HasContextTokens)
				assert.True(t, msgs[0].HasOutputTokens)
				assert.JSONEq(t, `{"input_tokens":0,"output_tokens":0,"cache_read_input_tokens":0,"cache_creation_input_tokens":0}`, string(msgs[0].TokenUsage))
			}
		})
	}
}

func TestOpenCodeV2CrossPathHistory(t *testing.T) {
	// Reproduced with 1.18.25: the v2 API accepts an existing CLI session
	// and appends projections without converting its older message/part rows.
	path, seed, writer := newTestDB(t)
	seed.AddProject("project-a", "/workspace/project-a")
	seed.AddSession("ses_a", "project-a", "", "", 1000, 5000)
	for i, text := range []string{"Earlier CLI prompt", "Legacy copy", "Later CLI prompt"} {
		id := fmt.Sprintf("msg_%d", i)
		seed.AddMessage(id, "ses_a", int64(i+1)*1000, int64(i+1)*1000, `{"role":"user"}`)
		seed.AddPart("prt_"+id, id, "ses_a", int64(i+1)*1000, int64(i+1)*1000, fmt.Sprintf(`{"type":"text","text":%q}`, text))
	}
	_, err := writer.ExecContext(t.Context(), openCodeV2TestSchema)
	require.NoError(t, err)
	_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES
 ('msg_1','ses_a','user',10,2000,2000,'{"text":"Projected copy"}'),
 ('msg_a','ses_a','assistant',20,2500,2500,'{"content":[{"type":"text","text":"First projected reply"}]}'),
 ('msg_b','ses_a','assistant',30,2400,2500,'{"content":[{"type":"text","text":"Second projected reply"}]}')`)
	require.NoError(t, err)
	sess, msgs, err := parseOpenCodeDBSession(path, "ses_a", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	require.Len(t, msgs, 5)
	assert.Equal(t, 3, sess.UserMessageCount)
	for i, want := range []string{"Earlier CLI prompt", "Projected copy", "First projected reply", "Second projected reply", "Later CLI prompt"} {
		assert.Equal(t, want, msgs[i].Content)
		assert.Equal(t, i, msgs[i].Ordinal)
	}
}

func TestOpenCodeV2UpgradeCoexistence(t *testing.T) {
	path, seed, writer := newTestDB(t)
	seed.AddProject("project-a", "/workspace/project-a")
	for _, id := range []string{"ses_a", "ses_b"} {
		seed.AddSession(id, "project-a", "", "", 1000, 2000)
		seed.AddMessage("msg_"+id, id, 1000, 1000, `{"role":"user"}`)
		seed.AddPart("prt_"+id, "msg_"+id, id, 1000, 1000, `{"type":"text","text":"Legacy prompt"}`)
	}
	// The beta migration leaves session/message/part in place and commits
	// session_v2 metadata plus all its projections together, one session at a time.
	_, err := writer.ExecContext(t.Context(), `CREATE TABLE session_v2 (
 id TEXT PRIMARY KEY, project_id TEXT NOT NULL, parent_id TEXT, title TEXT,
 directory TEXT NOT NULL, time_created INTEGER NOT NULL, time_updated INTEGER NOT NULL,
 time_idle INTEGER);
 INSERT INTO session_v2 VALUES ('ses_b','project-a',NULL,NULL,'/workspace/project-a',1000,2000,4000),
 ('ses_c','project-a',NULL,NULL,'/workspace/project-a',1000,2000,5000);`)
	require.NoError(t, err)
	_, err = writer.ExecContext(t.Context(), strings.ReplaceAll(openCodeV2TestSchema, "REFERENCES session(id)", "REFERENCES session_v2(id)"))
	require.NoError(t, err)
	_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES
 ('msg_ses_b','ses_b','user',1,1000,1000,'{"text":"Migrated prompt"}'),
 ('msg_ses_c','ses_c','user',1,1000,1000,'{"text":"Beta prompt"}')`)
	require.NoError(t, err)
	full, err := ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	watermarks, err := ListOpenCodeSessionWatermarkMeta(path)
	require.NoError(t, err)
	require.Len(t, full, 3)
	require.Len(t, watermarks, 3)
	for i, tc := range []struct {
		id, text string
		ended    int64
	}{
		{"ses_a", "Legacy prompt", 2000}, {"ses_b", "Migrated prompt", 4000}, {"ses_c", "Beta prompt", 5000},
	} {
		assert.Equal(t, tc.id, full[i].SessionID)
		assert.Equal(t, tc.id, watermarks[i].SessionID)
		assert.True(t, OpenCodeSQLiteSessionExists(t.Context(), path, tc.id))
		mtime, digest, composite, err := openCodeSessionCompositeMtime(t.Context(), writer, path, tc.id)
		require.NoError(t, err)
		assert.True(t, composite)
		assert.Equal(t, full[i].FileMtime, mtime*1_000_000)
		assert.Equal(t, full[i].ChildDigest, digest)
		sess, msgs, err := parseOpenCodeDBSession(path, tc.id, "host-a")
		require.NoError(t, err)
		require.NotNil(t, sess)
		require.Len(t, msgs, 1)
		assert.Equal(t, tc.text, msgs[0].Content)
		assert.True(t, time.UnixMilli(tc.ended).Equal(sess.EndedAt))
	}
	// Execution completion alone must advance both passive and active freshness.
	_, err = writer.ExecContext(t.Context(), "UPDATE session_v2 SET time_idle = 6000 WHERE id = 'ses_c'")
	require.NoError(t, err)
	next, err := ListOpenCodeSessionWatermarkMeta(path)
	require.NoError(t, err)
	require.Len(t, next, 3)
	assert.Equal(t, int64(6000_000_000), next[2].FileMtime)
	mtime, err := OpenCodeSourceMtime(t.Context(), path+"#ses_c")
	require.NoError(t, err)
	assert.Equal(t, int64(6000_000_000), mtime)
	// The producer keeps v1 rows after migration, including after v2 deletion.
	// Its descending cursor excludes copied IDs while older IDs remain visible.
	_, err = writer.ExecContext(t.Context(), `CREATE TABLE kv (key TEXT PRIMARY KEY, value TEXT NOT NULL);
 INSERT INTO kv VALUES ('migration.v1-v2', '{"phase":"sessions","cursor":"ses_b"}');
 DELETE FROM session_v2 WHERE id = 'ses_b'`)
	require.NoError(t, err)
	full, err = ListOpenCodeSessionMeta(path)
	require.NoError(t, err)
	require.Len(t, full, 2)
	assert.Equal(t, "ses_a", full[0].SessionID)
	assert.Equal(t, "ses_c", full[1].SessionID)
	assert.False(t, OpenCodeSQLiteSessionExists(t.Context(), path, "ses_b"))
	_, _, found, err := openCodeSQLiteSessionWatermarkOnly(t.Context(), path, "ses_b")
	require.NoError(t, err)
	assert.False(t, found)
	_, err = writer.ExecContext(t.Context(), `UPDATE kv SET value = '{"phase":"completed"}' WHERE key = 'migration.v1-v2'`)
	require.NoError(t, err)
	watermarks, err = ListOpenCodeSessionWatermarkMeta(path)
	require.NoError(t, err)
	require.Len(t, watermarks, 1)
	assert.Equal(t, "ses_c", watermarks[0].SessionID)
	assert.False(t, OpenCodeSQLiteSessionExists(t.Context(), path, "ses_a"))
}

func TestOpenCodeV2CapturedAttachmentCompaction(t *testing.T) {
	// Captured from beta 19381's prompt and compact APIs. The request had no
	// prompt text and carried input.txt as an inline text attachment.
	raw, err := os.ReadFile("testdata/opencode_v2/attachment_compaction.json")
	require.NoError(t, err)
	var rows []struct {
		ID      string         `json:"id"`
		Type    string         `json:"type"`
		Seq     int64          `json:"seq"`
		Created int64          `json:"time_created"`
		Updated int64          `json:"time_updated"`
		Data    jsontext.Value `json:"data"`
	}
	require.NoError(t, json.Unmarshal(raw, &rows))
	path, seed, writer := newTestDB(t)
	seed.AddProject("project-a", "/workspace/project-a")
	seed.AddSession("ses_a", "project-a", "", "", 1788977900000, 1788977920000)
	_, err = writer.ExecContext(t.Context(), openCodeV2TestSchema)
	require.NoError(t, err)
	for _, row := range rows {
		_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES (?, 'ses_a', ?, ?, ?, ?, ?)`, row.ID, row.Type, row.Seq, row.Created, row.Updated, string(row.Data))
		require.NoError(t, err)
	}
	sess, msgs, err := parseOpenCodeDBSession(path, "ses_a", "host-a")
	require.NoError(t, err)
	require.NotNil(t, sess)
	require.Len(t, msgs, 4)
	assert.Equal(t, 1, sess.UserMessageCount)
	assert.Equal(t, "[Attachment: input.txt]\nalpha\nbeta\ngamma\n", msgs[0].Content)
	assert.True(t, msgs[3].IsSystem)
	assert.True(t, msgs[3].IsCompactBoundary)
	assert.Contains(t, msgs[3].Content, "The user shared a file `input.txt` containing three lines")
}

func TestOpenCodeV2ToolFiles(t *testing.T) {
	// The file records follow the beta read tool's toModelContent output.
	raw, err := os.ReadFile("testdata/opencode_v2/tool_files.json")
	require.NoError(t, err)
	var source struct {
		Content []struct {
			State struct {
				Content []map[string]string `json:"content"`
			} `json:"state"`
		} `json:"content"`
	}
	require.NoError(t, json.Unmarshal(raw, &source))
	for _, status := range []string{"completed", "error"} {
		t.Run(status, func(t *testing.T) {
			path, seed, writer := newTestDB(t)
			seed.AddProject("project-a", "/workspace/project-a")
			seed.AddSession("ses_files", "project-a", "", "Files", 1700000000000, 1700000002000)
			_, err := writer.ExecContext(t.Context(), openCodeV2TestSchema)
			require.NoError(t, err)
			data := string(raw)
			if status == "error" {
				data = strings.ReplaceAll(data, `"status": "completed"`, `"status": "error", "error": {"message": "Read failed"}`)
			}
			_, err = writer.ExecContext(t.Context(), `INSERT INTO session_message VALUES ('msg_files', 'ses_files', 'assistant', 1, 1700000000000, 1700000002000, ?)`, data)
			require.NoError(t, err)
			_, messages, err := parseOpenCodeDBSession(path, "ses_files", "host-a")
			require.NoError(t, err)
			require.Len(t, messages, 1)
			require.Len(t, messages[0].ToolCalls, 2)
			for i, call := range messages[0].ToolCalls {
				require.Len(t, call.ResultEvents, 1)
				var blocks []map[string]string
				require.NoError(t, json.Unmarshal([]byte(call.ResultEvents[0].Content), &blocks))
				want := source.Content[i].State.Content
				if status == "error" {
					require.Len(t, blocks, len(want)+1)
					assert.Equal(t, map[string]string{"type": "text", "text": "Read failed"}, blocks[len(want)])
					assert.Equal(t, "errored", call.ResultEvents[0].Status)
				} else {
					require.Len(t, blocks, len(want))
					assert.Equal(t, "completed", call.ResultEvents[0].Status)
				}
				if i == 0 {
					assert.Equal(t, want[0], blocks[0])
					assert.Equal(t, "input_image", blocks[1]["type"])
					assert.Equal(t, want[1]["uri"], blocks[1]["image_url"])
					assert.Equal(t, "plot.png", blocks[1]["name"])
					assert.NotContains(t, blocks[1], "uri", "image policy must own the only payload copy")
					assert.Equal(t, want[2], blocks[2])
				} else {
					assert.Equal(t, want, blocks[:len(want)], "PDF, text payload, and external reference survive unchanged")
				}
			}
		})
	}
}
