// Code generated by "enumer -type=ZoomLevel -trimprefix=ZoomLevel -output=zoomlevel_enumer.go"; DO NOT EDIT.

package config

import (
	"fmt"
	"strings"
)

const _ZoomLevelName = "67758090100110120125130150175200"
const _ZoomLevelLowerName = "67758090100110120125130150175200"

var _ZoomLevelMap = map[ZoomLevel]string{
	67:  _ZoomLevelName[0:2],
	75:  _ZoomLevelName[2:4],
	80:  _ZoomLevelName[4:6],
	90:  _ZoomLevelName[6:8],
	100: _ZoomLevelName[8:11],
	110: _ZoomLevelName[11:14],
	120: _ZoomLevelName[14:17],
	125: _ZoomLevelName[17:20],
	130: _ZoomLevelName[20:23],
	150: _ZoomLevelName[23:26],
	175: _ZoomLevelName[26:29],
	200: _ZoomLevelName[29:32],
}

func (i ZoomLevel) String() string {
	if str, ok := _ZoomLevelMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ZoomLevel(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ZoomLevelNoOp() {
	var x [1]struct{}
	_ = x[ZoomLevel67-(67)]
	_ = x[ZoomLevel75-(75)]
	_ = x[ZoomLevel80-(80)]
	_ = x[ZoomLevel90-(90)]
	_ = x[ZoomLevel100-(100)]
	_ = x[ZoomLevel110-(110)]
	_ = x[ZoomLevel120-(120)]
	_ = x[ZoomLevel125-(125)]
	_ = x[ZoomLevel130-(130)]
	_ = x[ZoomLevel150-(150)]
	_ = x[ZoomLevel175-(175)]
	_ = x[ZoomLevel200-(200)]
}

var _ZoomLevelValues = []ZoomLevel{ZoomLevel67, ZoomLevel75, ZoomLevel80, ZoomLevel90, ZoomLevel100, ZoomLevel110, ZoomLevel120, ZoomLevel125, ZoomLevel130, ZoomLevel150, ZoomLevel175, ZoomLevel200}

var _ZoomLevelNameToValueMap = map[string]ZoomLevel{
	_ZoomLevelName[0:2]:        ZoomLevel67,
	_ZoomLevelLowerName[0:2]:   ZoomLevel67,
	_ZoomLevelName[2:4]:        ZoomLevel75,
	_ZoomLevelLowerName[2:4]:   ZoomLevel75,
	_ZoomLevelName[4:6]:        ZoomLevel80,
	_ZoomLevelLowerName[4:6]:   ZoomLevel80,
	_ZoomLevelName[6:8]:        ZoomLevel90,
	_ZoomLevelLowerName[6:8]:   ZoomLevel90,
	_ZoomLevelName[8:11]:       ZoomLevel100,
	_ZoomLevelLowerName[8:11]:  ZoomLevel100,
	_ZoomLevelName[11:14]:      ZoomLevel110,
	_ZoomLevelLowerName[11:14]: ZoomLevel110,
	_ZoomLevelName[14:17]:      ZoomLevel120,
	_ZoomLevelLowerName[14:17]: ZoomLevel120,
	_ZoomLevelName[17:20]:      ZoomLevel125,
	_ZoomLevelLowerName[17:20]: ZoomLevel125,
	_ZoomLevelName[20:23]:      ZoomLevel130,
	_ZoomLevelLowerName[20:23]: ZoomLevel130,
	_ZoomLevelName[23:26]:      ZoomLevel150,
	_ZoomLevelLowerName[23:26]: ZoomLevel150,
	_ZoomLevelName[26:29]:      ZoomLevel175,
	_ZoomLevelLowerName[26:29]: ZoomLevel175,
	_ZoomLevelName[29:32]:      ZoomLevel200,
	_ZoomLevelLowerName[29:32]: ZoomLevel200,
}

var _ZoomLevelNames = []string{
	_ZoomLevelName[0:2],
	_ZoomLevelName[2:4],
	_ZoomLevelName[4:6],
	_ZoomLevelName[6:8],
	_ZoomLevelName[8:11],
	_ZoomLevelName[11:14],
	_ZoomLevelName[14:17],
	_ZoomLevelName[17:20],
	_ZoomLevelName[20:23],
	_ZoomLevelName[23:26],
	_ZoomLevelName[26:29],
	_ZoomLevelName[29:32],
}

// ZoomLevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ZoomLevelString(s string) (ZoomLevel, error) {
	if val, ok := _ZoomLevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ZoomLevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ZoomLevel values", s)
}

// ZoomLevelValues returns all values of the enum
func ZoomLevelValues() []ZoomLevel {
	return _ZoomLevelValues
}

// ZoomLevelStrings returns a slice of all String values of the enum
func ZoomLevelStrings() []string {
	strs := make([]string, len(_ZoomLevelNames))
	copy(strs, _ZoomLevelNames)
	return strs
}

// IsAZoomLevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ZoomLevel) IsAZoomLevel() bool {
	_, ok := _ZoomLevelMap[i]
	return ok
}
